export const serviceTypes = [
  "Event-planning",
  "Catering",
  "Photography",
  "Videography",
  "Music & Entertainment",
  "Floral Design",
  "Decor & Styling",
  "Beauty Services",
  "Bartending",
  "Event Staffing",
  "Transportation",
  "Rentals",
  "Cakes & Desserts",
  "Security Services",
  "Consulting",
  "Other",
];
