import { v4 as uuidv4 } from 'uuid';

export interface Review {
  id: string;
  user: string; // Mocked as string UUID
  rating: number;
  comment?: string;
  target: string; // Venue or Service ID
  targetModel: 'Venue' | 'Service';
  isDeleted: boolean;
  createdAt: Date;
  updatedAt: Date;
}

export const reviews: Review[] = [
  {
    id: uuidv4(),
    user: uuidv4(),
    rating: 5,
    comment: "Absolutely loved this venue! The ambiance was perfect.",
    target: uuidv4(),
    targetModel: 'Venue',
    isDeleted: false,
    createdAt: new Date('2025-01-10'),
    updatedAt: new Date('2025-01-10'),
  },
  {
    id: uuidv4(),
    user: uuidv4(),
    rating: 4,
    comment: "Great service, but the parking situation could be better.",
    target: uuidv4(),
    targetModel: 'Service',
    isDeleted: false,
    createdAt: new Date('2025-02-15'),
    updatedAt: new Date('2025-02-15'),
  },
  {
    id: uuidv4(),
    user: uuidv4(),
    rating: 3,
    comment: "Decent place, but it was a bit noisy for our event.",
    target: uuidv4(),
    targetModel: 'Venue',
    isDeleted: false,
    createdAt: new Date('2025-03-05'),
    updatedAt: new Date('2025-03-05'),
  },
  {
    id: uuidv4(),
    user: uuidv4(),
    rating: 5,
    comment: "Fantastic staff! They made sure everything ran smoothly.",
    target: uuidv4(),
    targetModel: 'Service',
    isDeleted: false,
    createdAt: new Date('2025-04-20'),
    updatedAt: new Date('2025-04-20'),
  },
  {
    id: uuidv4(),
    user: uuidv4(),
    rating: 2,
    comment: "Not what I expected. The pictures looked better than reality.",
    target: uuidv4(),
    targetModel: 'Venue',
    isDeleted: false,
    createdAt: new Date('2025-05-10'),
    updatedAt: new Date('2025-05-10'),
  },
  {
    id: uuidv4(),
    user: uuidv4(),
    rating: 2,
    comment: "Not what I expected. The pictures looked better than reality.",
    target: uuidv4(),
    targetModel: 'Venue',
    isDeleted: false,
    createdAt: new Date('2025-05-10'),
    updatedAt: new Date('2025-05-10'),
  },
  {
    id: uuidv4(),
    user: uuidv4(),
    rating: 2,
    comment: "Not what I expected. The pictures looked better than reality.",
    target: uuidv4(),
    targetModel: 'Venue',
    isDeleted: false,
    createdAt: new Date('2025-05-10'),
    updatedAt: new Date('2025-05-10'),
  },
  {
    id: uuidv4(),
    user: uuidv4(),
    rating: 2,
    comment: "Not what I expected. The pictures looked better than reality.",
    target: uuidv4(),
    targetModel: 'Venue',
    isDeleted: false,
    createdAt: new Date('2025-05-10'),
    updatedAt: new Date('2025-05-10'),
  },
  {
    id: uuidv4(),
    user: uuidv4(),
    rating: 2,
    comment: "Not what I expected. The pictures looked better than reality.",
    target: uuidv4(),
    targetModel: 'Venue',
    isDeleted: false,
    createdAt: new Date('2025-05-10'),
    updatedAt: new Date('2025-05-10'),
  },
  {
    id: uuidv4(),
    user: uuidv4(),
    rating: 2,
    comment: "Not what I expected. The pictures looked better than reality.",
    target: uuidv4(),
    targetModel: 'Venue',
    isDeleted: false,
    createdAt: new Date('2025-05-10'),
    updatedAt: new Date('2025-05-10'),
  },
  {
    id: uuidv4(),
    user: uuidv4(),
    rating: 2,
    comment: "Not what I expected. The pictures looked better than reality.",
    target: uuidv4(),
    targetModel: 'Venue',
    isDeleted: false,
    createdAt: new Date('2025-05-10'),
    updatedAt: new Date('2025-05-10'),
  },
  {
    id: uuidv4(),
    user: uuidv4(),
    rating: 2,
    comment: "Not what I expected. The pictures looked better than reality.",
    target: uuidv4(),
    targetModel: 'Venue',
    isDeleted: false,
    createdAt: new Date('2025-05-10'),
    updatedAt: new Date('2025-05-10'),
  },
  {
    id: uuidv4(),
    user: uuidv4(),
    rating: 2,
    comment: "Not what I expected. The pictures looked better than reality.",
    target: uuidv4(),
    targetModel: 'Venue',
    isDeleted: false,
    createdAt: new Date('2025-05-10'),
    updatedAt: new Date('2025-05-10'),
  },
  {
    id: uuidv4(),
    user: uuidv4(),
    rating: 2,
    comment: "Not what I expected. The pictures looked better than reality.",
    target: uuidv4(),
    targetModel: 'Venue',
    isDeleted: false,
    createdAt: new Date('2025-05-10'),
    updatedAt: new Date('2025-05-10'),
  },
];